# Generated by Django 3.0 on 2025-03-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
