# Generated by Django 3.0 on 2025-03-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250321_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectname',
            field=models.CharField(max_length=5000),
        ),
    ]
