"""chatbot URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns =[
    path('logout/',views.logout),
    path('login/',views.login),
    path('login_post/', views.login_post),
    path('addcourse/',views.addcourse),
    path('delcourse/<id>', views.delcourse),
    path('addcourse_post/',views.addcourse_post),
    path('addept/', views.addept),
    path('addept_post/', views.addept_post),
    path('eddept/<id>',views.eddept),
    path('eddept_post/',views. eddept_post),
    path('deldept/<id>',views.deldept),
    # path('addevent/', views.addevent),
    # path('addevent_post/', views.addevent_post),
    path('delevent/<id>', views.delevent),
    path('addfacility/', views.addfacility),
    path('addfacility_post/', views.addfacility_post),
    path('delfacility/<id>', views.delfacility),
    path('addschedule/', views.addschedule),
    path('addschedule_post/', views.addschedule_post),
    path('email_exist/', views.email_exist),
    path('addstaff/', views.addstaff),
    path('addstaff_post/', views.addstaff_post),
    path('delstaff/<id>', views.delstaff),
    path('addstudent/', views.addstudent),
    path('delstudent/<id>', views.delstudent),
    path('addstudent_post/', views.addstudent_post),
    path('addsub/', views.addsub),
    path('addsub_post/', views.addsub_post),
    path('delsub/<id>', views.delsub),
    path('addsupport/', views.addsupport),
    path('addsupport_post/', views.addsupport_post),
    path('delsupport/<id>', views.delsupport),
    path('allostaff/', views.allostaff),
    path('allostaff_post/', views.allostaff_post),
    path('delallostaff/<id>', views.delallostaff),
    path('changepass/', views.changepass),
    path('changepass_post/', views.changepass_post),
    path('edallostaff/<id>', views.edallostaff),
    path('edallostaff_post/', views.edallostaff_post),
    path('edcourse/<id>', views.edcourse),
    path('edcourse_post/', views.edcourse_post),
    path('edevent/', views.edevent),
    path('edevent_post/', views.edevent_post),
    path('delevent/', views.delevent),
    path('edfacility/<id>', views.edfacility),
    path('edfacility_post/', views.edfacility_post),
    path('edschedule/<id>', views.edschedule),
    path('edschedule_post/', views.edschedule_post),
    path('delschedule/<id>', views.delschedule),
    path('edstaff/<id>', views.edstaff),
    path('edstaff_post/', views.edstaff_post),
    path('edstud/<id>', views.edstud),
    path('edstud_post/', views.edstud_post),
    path('edsub/<id>', views.edsub),
    path('edsub_post/', views.edsub_post),
    path('edsuprt/<id>', views.edsuprt),
    path('edsuprt_post/', views.edsuprt_post),
    path('feedback/', views.feedback),
    path('feedback_post/', views.feedback_post),
    path('gallery/', views.gallery),
    path('gallery_post/', views.gallery_post),
    path('sendrply/<id>', views.sendrply),
    path('sendrply_post/', views.sendrply_post),
    path('updept/', views.updept),
    path('updept_post/', views.updept_post),
    path('addhostel/',views.addhostel),
    path('addhostel_post/',views.addhostel_post),
    path('viewhostel/',views.viewhostel),
    path('edhostel/<id>',views.edhostel),
    path('edhostel_post/',views.edhostel_post),
    path('delhostel/<id>',views.delhostel),
    path('viewallo/', views.viewallo),
    path('viewallo_post/', views.viewallo_post),
    path('viewcmpnt/', views.viewcmpnt),
    path('viewcmpnt_post/', views.viewcmpnt_post),
    path('viewcou/', views.viewcou),
    path('viewcou_post/', views.viewcou_post),
    path('viewdept/', views.viewdept),
    path('viewdept_post/', views.viewdept_post),
    path('viewevent/', views.viewevent),
    path('viewevent_post/', views.viewevent_post),
    path('viewfacility/', views.viewfacility),
    path('viewfacility_post/', views.viewfacility_post),
    path('viewgallary/', views.viewgallery),
    path('viewgallary_post/', views.viewgallery_post),
    path('viewschedule/', views.viewschedule),
    path('viewschedule_post/', views.viewschedule_post),
    path('viewstaff/', views.viewstaff),
    path('viewstaff_post/', views.viewstaff_post),
    path('viewstu/', views.viewstu),
    path('viewstu_post/', views.viewstu_post),
    path('viewsub/', views.viewsub),
    path('viewsub_post/', views.viewsub_post),
    path('viewsuprt/', views.viewsuprt),
    path('viewsuprt_post/', views.viewsuprt_post),
    path('adminhome/', views.adminhome),
    path('staffhome/', views.staffhome),
    path('s_viewprofile/', views.s_viewprofile),
    path('s_addevent/',views.s_addevent),
    path('s_addeventpost/',views.s_addeventpost),
    path('s_viewevent/',views.s_viewevent),
    path('s_vieweventpost/',views.s_vieweventpost),
    path('s_viewdept/', views.s_viewdept),
    path('s_viewdeptpost/',views.s_viewdeptpost),
    path('s_viewcou/', views. s_viewcou),
    path('s_viewcoupost/', views. s_viewcoupost),
    path('s_viewallo/', views. s_viewallo),
    path('s_viewfacility/', views.s_viewfacility),
    path('s_addsfacility/',views.s_addsfacility),
    path('s_viewschedule/', views.s_viewschedule),
    path('s_viewsupport/', views.s_viewsupport),
    # path('s_viewstu/', views.s_viewstu),
    path('s_sendcmplnt/', views.s_sendcmplnt),
    path('s_sendcmplntpost/',views.s_sendcmplntpost),
    path('s_viewrply/', views.s_viewrply),
    path('s_viewrplypost/',views.s_viewrplypost),
    path('s_sendfeed/', views.s_sendfeed),
    path('s_sendfeedpost/',views.s_sendfeedpost),
    path('s_edgallery/', views.s_edgallery),
    path('s_viewprofile/',views.s_viewprofile),
    path('s_viewstudent/',views.s_viewstudent),
    path('s_addfacility/',views.s_addfacility),
    path('s_addfacility_post/',views.s_addfacility_post),
    path('s_addgallery/',views.s_addgallery),
    path('s_addgallerypost/',views.s_addgallerypost),
    path('s_viewgallery/',views.s_viewgallery),
    path('s_viewgallerypost/',views.s_viewgallerypost),
    path('s_edgallery/<id>',views.s_edgallery),
    path('s_edgallerypost/',views.s_edgallerypost),
    path('s_dltgallery/<id>',views.s_dltgallery),
    path('s_viewfacility/',views.s_viewfacility),
    path('s_viewfacilitypost/',views.s_viewfacilitypost),
    path('s_addfacility_post/',views.s_addfacility_post),
    path ('s_edfacility/<id>',views.s_edfacility),
    path('s_edfacilitypost/',views.s_edfacilitypost),
    path('s_dlfacility/<id>',views.s_dlfacility),
    path('s_viewallo/',views.s_viewallo),
    path('s_viewstudent/',views.s_viewstudent),
    path('s_viewstudentpost/',views.s_viewstudentpost),
    path('s_viewsupport/',views.s_viewsupport),
    path('s_viewsupportpost/',views.s_viewsupportpost),
    path('s_edevent/<id>',views.s_edevent),
    path('s_edeventpost/',views.s_edeventpost),
    path('s_delevent/<id>',views.s_delevent),
    path('s_bus/',views.s_bus),
    path('s_buspost/',views.s_buspost),
    path('edbus/<id>',views.edbus),
    path('edbus_post/',views.edbus_post),
    path('delbus/<id>',views.delbus),
    path('viewbus/',views.viewbus),
    path('viewbus_post/',views.viewbus_post),
    path('phome/',views.phome),
    path('p_viewdept/',views.p_viewdept),
    path('p_viewstaff/',views.p_viewstaff),
    path('p_viewstaffpost/',views.p_viewstaffpost),
    path('p_viewgallery/',views.p_viewgallery),
    path('p_viewgallerypost/',views.p_viewgallerypost),
    path('p_viewfacility/',views.p_viewfacility),
    path('p_viewfacilitypost/',views.p_viewfacilitypost),
    path('p_viewcource/',views.p_viewcource),
    path('p_viewcourcepost/',views.p_viewcourcepost),
    path('p_viewschedule/',views.p_viewschedule),
    path('p_viewsub/',views.p_viewsub),
    path('p_viewsubpost/',views.p_viewsubpost),
    path('p_viewsupport/',views.p_viewsupport),
    path('p_viewsupportpost/',views.p_viewsupportpost),
    path('p_viewevent/',views.p_viewevent),
    path('p_vieweventpost/',views.p_vieweventpost),
    path('p_sendfeedback/',views.p_sendfeedback),
    path('p_sendfeedbackpost/',views.p_sendfeedbackpost),
    path('p_viewbus/',views.p_viewbus),
    path('p_viewbus_post/',views.p_viewbus_post),
    path('p_vfeedback/',views.p_vfeedback),
    path('p_viewhostel/',views.p_viewhostel),
    path('chat/<msg>',views.chat),
    path('chat1/',views.chat1),
    # path('chat_view/',views.chat_view),
    path('chat_send/<msg>',views.chat),
    path('alg/',views.alg),
    path('check_session/',views.check_session),

]
